spring.application.name=otp-service

server.port=8080

spring.jackson.time-zone=UTC

logging.level.root=INFO
logging.level.org.springframework.web=INFO

jwt.secret=change_this_to_a_very_long_secret_key_for_hs256_signing_123456
jwt.expiration-minutes=60

email.username=vkuryndin@gmail.com
email.from=vkuryndin@gmail.com
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
email.password=