spring.application.name=otp-service

server.port=8080

spring.jackson.time-zone=UTC

logging.level.root=INFO
logging.level.org.springframework.web=INFO

otp.generate-rate-limit.enabled=true
otp.generate-rate-limit.max-attempts=5
otp.generate-rate-limit.window-seconds=60

session.cleanup.fixed-delay-ms=300000

jwt.secret=change_this_to_a_very_long_secret_key_for_hs256_signing_123456
jwt.expiration-minutes=60

email.username=vkuryndin@gmail.com
email.from=vkuryndin@gmail.com
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
email.password=kyzd cfpb srlz vihi

telegram.bot-token=8611712371:AAHBsJ48eMOuiYbbexRXdBohlgUc_VTcdSQ
telegram.api-url=https://api.telegram.org

telegram.bot-username=KuryndinOptServiceBot
telegram.bind-expiration-minutes=15


smpp.host=localhost
smpp.port=2775
smpp.system-id=smppclient1
smpp.password=password
smpp.system-type=OTP
smpp.source-addr=OTPService

logging.file.name=logs/otp-service.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n