### Base variables
@host = http://localhost:8080
###@adminToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI2IiwibG9naW4iOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3Njc4Nzc1MCwiZXhwIjoxNzc2NzkxMzUwfQ.RYEl5qVgmjixZN7UwW3lI8CkqXRg8C3JxgzLmpY6Ofa2jfyDJ8r-udICfopZtoec
###@userToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMSIsImxvZ2luIjoidXNlcl8yIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NzY4ODQzNjIsImV4cCI6MTc3Njg4Nzk2Mn0.cVY1pxQ0y4TF0dwqAHd3S3TpSjukdTtBwyVBdywk8TMSuyDxL9VVdU6XvrjVDWDv
@userId = 5
@otpFile = otp-codes.txt
@otpCode = 599987

### =====================================
### 0. FAST LOGIN
### =====================================

### Login as admin - valid
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "12345678"
}
> {%
    client.global.set("adminToken", response.body.token);
    client.log("adminToken = " + client.global.get("adminToken"));
%}


### Login as user - valid
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "user_4",
  "password": "12345678"
}
> {%
    client.global.set("userToken", response.body.token);
    client.log("userToken = " + client.global.get("userToken"));
%}


### Login as user - valid
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "user_5",
  "password": "12345678"
}
> {%
    client.global.set("userToken", response.body.token);
    client.log("userToken = " + client.global.get("userToken"));
%}


### Login as user - valid
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "user_7",
  "password": "12345678"
}

> {%
    client.global.set("userToken", response.body.token);
    client.log("userToken = " + client.global.get("userToken"));
%}

### =====================================
### 1. HEALTH
### =====================================

### Health check
GET {{host}}/health
Accept: text/plain

### Database health check
GET {{host}}/health/db
Accept: application/json

### =====================================
### 2. REGISTER - SUCCESS CASES
### =====================================

### Register admin - valid
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "admin",
  "password": "12345678",
  "role": "ADMIN",
  "email": "admin@test.com"
}

### Register user - valid
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "user_3",
  "password": "12345678",
  "role": "USER",
  "email": "user2@test.com",
  "phone": "+37400112233",
  "telegramChatId": "123456789"
}


### Register user - valid
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "user_4",
  "password": "12345678",
  "role": "USER",
  "email": "user2@test.com",
  "phone": "+37400112233",
  "telegramChatId": "123456789"
}

### Register user - valid
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "user_2",
  "password": "12345678",
  "role": "USER",
  "email": "v.kuryndin@proresearch.am",
  "phone": "+37400112233",
  "telegramChatId": "123456789"
}

### Register user - valid
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "user_5",
  "password": "12345678",
  "role": "USER",
  "email": "tatiana.kuryndina@gmail.com",
  "phone": "+37400112233",
  "telegramChatId": "123456789"
}

### Register user - valid
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "user_6",
  "password": "12345678",
  "role": "USER",
  "email": "polly.volkova.08@mail.ru",
  "phone": "+37400112233",
  "telegramChatId": "123456789"
}

### Register user - valid
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "user_7",
  "password": "12345678",
  "role": "USER",
  "email": "akondratev01@gmail.com",
  "phone": "+37400112233",
  "telegramChatId": "123456789"
}

### =====================================
### 3. REGISTER - VALIDATION ERRORS
### =====================================

### Register - login is required
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "",
  "password": "12345678",
  "role": "USER"
}

### Register - login too short
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "ab",
  "password": "12345678",
  "role": "USER"
}

### Register - login invalid chars
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "user!*",
  "password": "12345678",
  "role": "USER"
}

### Register - password is required
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "user2",
  "password": "",
  "role": "USER"
}

### Register - password too short
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "user3",
  "password": "1234567",
  "role": "USER"
}

### Register - role is required
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "user4",
  "password": "12345678"
}

### =====================================
### 4. REGISTER - BUSINESS RULE ERRORS
### =====================================

### Register - duplicate login
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "admin",
  "password": "12345678",
  "role": "USER"
}

### Register - second admin
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "admin2",
  "password": "12345678",
  "role": "ADMIN"
}

### =====================================
### 5. LOGIN
### =====================================

### Login as admin - valid
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "12345678"
}

### Login as user - valid
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "user_3",
  "password": "12345678"
}

### Login as user - valid
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "user_2",
  "password": "12345678"
}

### Login as user - valid
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "user_4",
  "password": "12345678"
}

### Login as user - valid
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "user_6",
  "password": "12345678"
}


### Login - login is required
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "",
  "password": "12345678"
}

### Login - password is required
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": ""
}

### Login - wrong password
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "wrongpass123"
}

### Login - user not found
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "unknown_user",
  "password": "12345678"
}

### =====================================
### 6. ADMIN API - AUTHORIZATION CHECKS
### =====================================

### Get all non-admin users as admin
GET {{host}}/admin/users
Authorization: Bearer {{adminToken}}
Accept: application/json

### Get all non-admin users - no token
GET {{host}}/admin/users
Accept: application/json

### Get all non-admin users - invalid token format
GET {{host}}/admin/users
Authorization: Token abc123
Accept: application/json

### Get all non-admin users as normal user
GET {{host}}/admin/users
Authorization: Bearer {{userToken}}
Accept: application/json

### =====================================
### 7. DELETE TESTS
### =====================================

### users delete test
### Delete user as admin
DELETE {{host}}/admin/users/{{userId}}
Authorization: Bearer {{adminToken}}
Accept: application/json

### Delete user as normal user
DELETE {{host}}/admin/users/{{userId}}
Authorization: Bearer {{userToken}}
Accept: application/json

### Delete user - no token
DELETE {{host}}/admin/users/{{userId}}
Accept: application/json

### Delete user - not found
DELETE {{host}}/admin/users/999999
Authorization: Bearer {{adminToken}}
Accept: application/json


### =====================================
### 8. LOGOUT
### =====================================

### Logout (valid token)
POST {{host}}/auth/logout
Authorization: Bearer {{adminToken}}
Accept: application/json

### Logout (valid token)
POST {{host}}/auth/logout
Authorization: Bearer {{userToken}}
Accept: application/json

### Logout - no token
POST {{host}}/auth/logout
Accept: application/json

### Logout - invalid token
POST {{host}}/auth/logout
Authorization: Bearer invalid_token
Accept: application/json

### =====================================
### 9. OTP - GET
### =====================================

### Get OTP config as admin
GET {{host}}/admin/otp-config
Authorization: Bearer {{adminToken}}
Accept: application/json

### Get OTP config as user
GET {{host}}/admin/otp-config
Authorization: Bearer {{userToken}}
Accept: application/json

### Get OTP config - no token
GET {{host}}/admin/otp-config
Accept: application/json

### Get OTP config - bad auth format
GET {{host}}/admin/otp-config
Authorization: Token abc123
Accept: application/json



### =====================================
### 10. OTP - UPDATE
### =====================================

### Update OTP config as admin
PUT {{host}}/admin/otp-config
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "codeLength": 6,
  "ttlSeconds": 1000
}

### Update OTP config as user
PUT {{host}}/admin/otp-config
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "codeLength": 6,
  "ttlSeconds": 300
}

### Update OTP config - invalid codeLength
PUT {{host}}/admin/otp-config
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "codeLength": 3,
  "ttlSeconds": 300
}

### Update OTP config - invalid ttl
PUT {{host}}/admin/otp-config
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "codeLength": 6,
  "ttlSeconds": 0
}

### Update OTP config - missing codeLength
PUT {{host}}/admin/otp-config
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "ttlSeconds": 300
}

### Update OTP config - missing ttlSeconds
PUT {{host}}/admin/otp-config
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "codeLength": 6
}


### =====================================
### 11. OTP - GENERATE
### =====================================

### Generate OTP as user
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-001",
  "deliveryChannel": "FILE",
  "deliveryTarget": "otp-codes.txt"
}

### Generate OTP as admin
POST {{host}}/otp/generate
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "operationId": "admin-op-001",
  "deliveryChannel": "FILE",
  "deliveryTarget": "otp-codes.txt"
}

### Generate OTP - no token
POST {{host}}/otp/generate
Content-Type: application/json

{
  "operationId": "payment-002",
  "deliveryChannel": "FILE",
  "deliveryTarget": "otp-codes.txt"
}

### Generate OTP - missing operationId
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "deliveryChannel": "FILE",
  "deliveryTarget": "otp-codes.txt"
}

### Generate OTP - missing deliveryChannel
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-003",
  "deliveryTarget": "otp-codes.txt"
}

### Generate OTP - missing deliveryTarget
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-004",
  "deliveryChannel": "FILE"
}

### VALIDATE

### Validate OTP as user
POST {{host}}/otp/validate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-telegram-001",
  "code": "{{otpCode}}"
}

### Validate OTP - wrong code
POST {{host}}/otp/validate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-001",
  "code": "000000"
}

### Validate OTP - missing operationId
POST {{host}}/otp/validate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "code": "123456"
}

### Validate OTP - missing code
POST {{host}}/otp/validate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-001"
}

### Validate OTP - no token
POST {{host}}/otp/validate
Content-Type: application/json

{
  "operationId": "payment-001",
  "code": "123456"
}



####

### Generate OTP to file as admin
POST {{host}}/otp/generate
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "operationId": "payment-file-001",
  "deliveryChannel": "FILE",
  "deliveryTarget": "{{otpFile}}"
}


### Generate OTP to file as user
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-file-001",
  "deliveryChannel": "FILE",
  "deliveryTarget": "{{otpFile}}"
}
### Generate OTP - unsupported channel
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-email-001",
  "deliveryChannel": "EMAIL",
  "deliveryTarget": "user@test.com"
}
### Validate OTP from file
POST {{host}}/otp/validate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-file-001",
  "code": "{{otpCode}}"
}

### test e-mail

@emailTarget = YOUR_REAL_EMAIL

### Generate OTP to email as user
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-email-001",
  "deliveryChannel": "EMAIL",
  "deliveryTarget": "{{emailTarget}}"
}

### Generate OTP to file as user
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-file-001",
  "deliveryChannel": "FILE",
  "deliveryTarget": "{{otpFile}}"
}
###

### Generate OTP to email as user
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-email-001",
  "deliveryChannel": "EMAIL"
}


### Generate OTP to telegram as user
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-telegram-001",
  "deliveryChannel": "TELEGRAM"
}
### Generate OTP to telegram as admin
POST {{host}}/otp/generate
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "operationId": "payment-telegram-admin-001",
  "deliveryChannel": "TELEGRAM"
}


### Start Telegram binding as user
POST {{host}}/telegram/bind/start
Authorization: Bearer {{userToken}}
Accept: application/json

### Start Telegram binding as admin
POST {{host}}/telegram/bind/start
Authorization: Bearer {{adminToken}}
Accept: application/json

### Start Telegram binding - no token
POST {{host}}/telegram/bind/start
Accept: application/json


### Start Telegram binding as user
POST {{host}}/telegram/bind/start
Authorization: Bearer {{userToken}}
Accept: application/json

### Complete Telegram binding as user
POST {{host}}/telegram/bind/complete
Authorization: Bearer {{userToken}}
Accept: application/json



### Generate OTP to SMS as user
POST {{host}}/otp/generate
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "operationId": "payment-sms-001",
  "deliveryChannel": "SMS"
}
### Generate OTP to SMS as admin
POST {{host}}/otp/generate
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "operationId": "payment-sms-admin-001",
  "deliveryChannel": "SMS"
}